Oguz
x-technology/airbnb-analytics pull request #2
Opened 2021-02-25 08:15 UTC by oguzerdo

Hi Igor hope you are well. When I'm trying to get amentities this column got empty and I realize that there were a cookie policy warner. I added a element click code and bingo! also I added a setup for no load images. Maybe you want to use, thanks for all, cya!

2021-02-25 09:20 UTC, smithio commented
Hey @oguzerdo , great to see you here!
Thanks a lot for your PR, it looks like a great improvement.
I will take a closer look and get back to you.

2021-02-26 21:12 UTC, smithio commented on Part 1 - Web Scraping/airbnb_parser.py
> +    driver = webdriver.Chrome(options=options, chrome_options=chrome_options)
since `chrome_options` raises DeprecationWarning, we could add the same to `options`:
options.add_argument('--blink-settings=imagesEnabled=false')

2021-02-26 21:15 UTC, smithio requested changes
Looks great! These changes will definitely improve the functionality.
Just one minor thing: what do you think of using `options` instead of `chrome_options`? It won't raise a warning + will make the code slightly shorter.

2021-02-27 07:25 UTC, oguzerdo commented
> Looks great! These changes will definitely improve the functionality.
> Just one minor thing: what do you think of using `options` instead of `chrome_options`? It won't raise a warning + will make the code slightly shorter.

Of course, I added it like this because I found it first when I searched. but much better what you suggested

2021-02-27 12:05 UTC, smithio approved these changes
Thank you, looks good!

2021-02-27 12:05 UTC, merged